name: Codespell - Spellcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    # docs: https://github.com/telekom-mms/.github#codespell
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@4c9b11997aa36fc74db64e5857d775ed66e86c9b" # main
