name: Prettify Markdown

on:
  push:
    branches: [main]

jobs:
  prettier-md:
    # docs: https://github.com/telekom-mms/.github#prettier-md
    uses: "telekom-mms/.github/.github/workflows/prettier-md.yml@0c3f6c78a37c4227f48ddf7fe9f8aca7798de14e" # main
