name: Prettify Markdown

on:
  push:
    branches: [main]

jobs:
  prettier-md:
    # docs: https://github.com/telekom-mms/.github#prettier-md
    uses: "telekom-mms/.github/.github/workflows/prettier-md.yml@4c9b11997aa36fc74db64e5857d775ed66e86c9b" # main
